private = { ignore = true }
accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "Zlib",
    "MIT-0",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0",
    "Apache-2.0 WITH LLVM-exception",
    "OFL-1.1",
    "Ubuntu-font-1.0",
]
