[package]
name = "ui"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
bevy_egui = { version = "0.34.1", default-features = false, features = ["render", "default_fonts"] }
bevy = { workspace = true, default-features = false }

[features]
default = []
dev = []
windows = []
linux = []
macos = []
