[package]
name = "utils"
description = "Crate containing helpers, macros and utilities for use in all other crates"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license-file.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
config = { workspace = true }
utils_macros = { path = "macros" }
bevy = { workspace = true, features = ["bevy_log"] }
crossbeam-channel = "0.5.15"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["json"] }

[features]
default = []
dev = [
  "config/dev"
]
windows = [
  "config/windows"
]
linux = [
  "config/linux"
]
macos = [
  "config/macos"
]
