[package]
name = "core"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
crossbeam-channel = "*"
image = { version = "*", default-features = false }
serde = { version = "*", default-features = false }
serde_json = "1.0.140"
bevy = { workspace = true, features = [
  "bevy_state",
  "bevy_log",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_sprite",
  "bevy_asset",
  "bevy_window",
  "serialize"
] }

[features]
dev = [
  "bevy/trace",
  "bevy/track_location"
]

windows = []
linux = []
macos = []
