[package]
name = "dungeonrs_core"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true, features = [
  "bevy_state",
  "bevy_log",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_sprite",
  "bevy_asset"
] }

[features]
dev = []

windows = []
linux = []
macos = []
