[package]
name = "dungeonrs_ui"
edition = "2024"
description = "Provides the user interface functionality, currently using egui but could switch to bevy_ui if it matures"
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_picking"] }
bevy-inspector-egui = { version = "0.31.0", default-features = false, features = [] }
bevy_egui = { version = "0.34.1", default-features = false, features = [
    "default_fonts",
    "picking",
    "render"
] }
