[package]
name = "dungeonrs_ui"
description = "Provides the user interface functionality, currently using egui but could switch to bevy_ui if it matures"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_picking", "bevy_render", "bevy_core_pipeline"] }
bevy-inspector-egui = { version = "0.31.0", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_image",
    "bevy_render",
] }
bevy_egui = { version = "0.34.1", default-features = false, features = [
    "default_fonts",
    "picking",
    "render"
] }
egui = { version = "0.31.1", default-features = false, features = [
    "mint"
] }

[features]
dev = [
    "egui/log",
    "egui/deadlock_detection"
]

windows = []
linux = []
macos = []
