[package]
name = "dungeonrs_editor"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
description = "The editor binary, this starts the UI and is intended to be the user facing binary"

[dependencies]
dungeonrs_ui = { path = "../ui" }
dungeonrs_core = { path = "../core" }
bevy = { workspace = true, features = [
    "multi_threaded",
    "bevy_window",
    "bevy_winit",
    "bevy_log",

    # image formats
    "png",
    "jpeg",
    "webp"
] }

[features]
default = ["dev"]
dev = [
    "bevy/dynamic_linking",
    "bevy/bevy_dev_tools",
    "bevy/bevy_debug_stepping",
    "bevy/bevy_gizmos",
    "bevy/file_watcher",
    "dungeonrs_core/dev",
    "dungeonrs_ui/dev"
]

windows = [
    "dungeonrs_core/windows",
    "dungeonrs_ui/windows"
]
linux = [
    "bevy/x11",
    "bevy/wayland",
    "bevy/accesskit_unix",
    "dungeonrs_core/linux",
    "dungeonrs_ui/linux"
]
macos = [
    "bevy/accesskit_unix",
    "dungeonrs_core/macos",
    "dungeonrs_ui/macos"
]

# Extended support for images, beyond the "default" image support (png, jpeg, webp)
images = [
    "bevy/hdr",
    "bevy/ktx2",
    "bevy/bmp",
    "bevy/dds",
    "bevy/exr",
    "bevy/ff",
    "bevy/gif",
    "bevy/ico",
    "bevy/pnm",
    "bevy/qoi",
    "bevy/tga",
    "bevy/tiff",
]
