[package]
name = "editor"
description = "The GUI binary that sets up the windows for the users to interact with."
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
data = { path = "../data" }
bevy = { workspace = true, default-features = false, features = [
  "std",
  "bevy_window",
  "bevy_winit",
  "bevy_asset"
] }

[target.'cfg(windows)'.build-dependencies]
image = { version = "0.25.6", default-features = false, features = ["png", "ico"] }
winresource = "0.1.20"

[features]
default = []
dev = [
  "data/dev"
]
windows = [
  "data/windows"
]
linux = [
  "data/linux"
]
macos = [
  "data/macos"
]
